name: Deliverytech CI/CD Pipeline

on: 
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Java 21
              uses: action/setup-java@v3
              with:
                java-version: '21'
                distribution: 'temurin'

            #- name: Build image Docker
            #  run: docker build -t delivery-tech:latest

            - name: Build with Maven
            # Utilizamos 'clean install' para compilar e empacotar
            # - DskipTests-true garante quenão rodaremos testes agora.cancel-timeout-minutes: 
              run: mvn clean package install -DskipTests=true


